
import java.awt.event.KeyEvent;
import java.io.BufferedInputStream;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
/**
 *
 * @author A G Aarafat
 */
public class onlinebankingg extends javax.swing.JFrame {
    
    
    int timeRun=0;
    

    /**
     * Creates new form onlinebankingg
     */
    public onlinebankingg() {
        initComponents();
        
        
       new Thread()
        {
            
            public void run()
            {
                while(timeRun==0)
                {
                    
                     Calendar cal=new GregorianCalendar();
                int hour=cal.get(Calendar.HOUR);
                int min=cal.get(Calendar.MINUTE);
                int sec=cal.get(Calendar.SECOND);
                int AM_PM=cal.get(Calendar.AM_PM);
                
                
                
                String day_night=" ";
                
                if(AM_PM==1)
                {
                    day_night="PM";
                    
                }
                else
                {
                    day_night="AM";
                    
                }
                
                String time=hour+" :"+min+" :"+sec+" "+day_night;
                
                clock.setText(time);
                    
                }
                
               
                
            }
            
        }.start();
                
        
        
        
    }
    
     private static final String USERNAME="root";
     private static final String PASSWORD="";
     private static final String CONN_STRING = "jdbc:mysql://localhost:3306/login?zeroDateTimeBehavior=convertToNull";  
     
     PreparedStatement pst=null;
     BufferedInputStream is = null;
     ResultSet rs=null;
     ResultSet ps=null;
     Connection conn = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clock = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tvaccout = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tvpass = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        picture = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(184, 206, 219));
        setMinimumSize(new java.awt.Dimension(611, 190));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clock.setBackground(new java.awt.Color(8, 219, 215));
        clock.setFont(new java.awt.Font("Algerian", 0, 18)); // NOI18N
        clock.setForeground(new java.awt.Color(0, 0, 102));
        clock.setText("10 : 25 : 25 PM");
        getContentPane().add(clock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 20, 130, 40));

        jLabel1.setBackground(new java.awt.Color(32, 156, 141));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(87, 19, 60));
        jLabel1.setText("Please  Sign Up Here");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 150, 30));

        jLabel2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(87, 19, 60));
        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 120, 30));

        jLabel3.setFont(new java.awt.Font("Rockwell", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(87, 19, 60));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 90, 30));

        tvaccout.setBackground(new java.awt.Color(218, 218, 218));
        tvaccout.setBorder(null);
        getContentPane().add(tvaccout, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 190, 30));

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 0));
        jButton1.setText("Sign In");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 90, 40));

        tvpass.setBackground(new java.awt.Color(218, 218, 218));
        tvpass.setBorder(null);
        getContentPane().add(tvpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 190, 30));

        jLabel4.setFont(new java.awt.Font("Sitka Small", 2, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(87, 19, 60));
        jLabel4.setText("You are not an Authorized Member ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 270, 50));

        jButton2.setFont(new java.awt.Font("Rockwell", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 153, 0));
        jButton2.setText("Sign Up");
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 260, 120, 50));

        jLabel5.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(86, 31, 81));
        jLabel5.setText("Online Banking System");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 300, 50));

        picture.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pexels-photo-203541(1).jpeg"))); // NOI18N
        getContentPane().add(picture, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 470));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if (tvaccout.getText().equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter user name","Error", JOptionPane.ERROR_MESSAGE);
           return;
            
            }
    String Password= String.valueOf(tvpass.getPassword());
        if (Password.equals("")) {
           JOptionPane.showMessageDialog( this, "Please enter password","Error", JOptionPane.ERROR_MESSAGE);
           return;
          
            }

     
             try {
                 String message=tvaccout.getText();
          
              conn = DriverManager.getConnection(CONN_STRING, USERNAME, PASSWORD);
              
              System.out.println("Connected");
              
               Statement stmnt = (Statement) conn.createStatement();
   
      
    String Query = "SELECT `createaccount` ,`createpassword` FROM `register` WHERE `createaccount`='"+message+"' AND `createpassword`='"+tvpass.getText()+"'";
    pst=conn.prepareStatement(Query);
                      
     
             //stmnt.execute(Query);
             
             rs=pst.executeQuery();
             
             if(rs.next())
             {
                 JOptionPane.showMessageDialog(null,"Access Granted");
                 
                homepage ho=new homepage();
                  ho.setVisible(true);
               this.setVisible(false);
                
             }
             else
             {
                 JOptionPane.showMessageDialog(null, "Invalid User!! Please Registar Here"
                         + "");
             }
        
             
             
   
              
              
          } catch (SQLException ex)
          
          {
              
          }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        
         Register r=new Register();
                  r.setVisible(true);
               this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(onlinebankingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(onlinebankingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(onlinebankingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(onlinebankingg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new onlinebankingg().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel clock;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel picture;
    private javax.swing.JTextField tvaccout;
    private javax.swing.JPasswordField tvpass;
    // End of variables declaration//GEN-END:variables
}
